#!/bin/bash

echo "roslaunch mmf_recorder_launch first.launch &"
roslaunch mmf_recorder_launch first.launch &
echo "sleep 5"
sleep 5
echo "roslaunch mmf_recorder_launch second.launch &"
roslaunch mmf_recorder_launch second.launch &
echo "sleep 5"
sleep 5
echo "lavis running!"
echo "press ctrl-c a couple of times in this terminal to stop all lavis processes."
sleep infinity
